// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initDB));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:DAL/Migrations/202401012008063_initDB.Designer.cs
            get { return "202401012008063_initDB"; }
========
            get { return "202401020433198_initDB"; }
>>>>>>>> 0df696cb3bc801d397c3a6ec355d5dbd241d7dfb:DAL/Migrations/202401020433198_initDB.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
